### ISSUE TITLE
Make projects carousel responsive 

### ISSUE THREAD

**Issue by andrescaro16** [Kilafy/kilafy#2]
### Describe the feature

We need the carousel section with the projects made by Kilafy to be responsive as well as the rest of the landing page.

### It should be implemented because

Because it will Improve the usability and user experience on smaller devices.

### Put here any screenshots or videos of what you would like to see (optional)

It should look like this:
![Screenshot from 2024-06-22 13-35-36](https://github.com/SoftwareForgeDevelopers/kilafy/assets/88978612/dfd6a4b5-fac9-42cc-92c5-1b4520255a45)

### Would you like to work on this issue?

None

**Comment by FelipeArredond** [comment]
Fixed
